# Generated by Django 6.0.1 on 2026-01-07 21:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('addon_type', models.CharField(choices=[('extension', 'Estensione durata'), ('magnet', 'Fissaggio magnetico'), ('engraving', 'Incisione nome')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('name_it', models.CharField(blank=True, max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('name_es', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('description_it', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_es', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('extension_years', models.PositiveIntegerField(default=0, help_text='Anni aggiuntivi (solo per addon tipo extension)')),
                ('applies_to_profile', models.BooleanField(default=False, help_text='Si applica al profilo (es. estensione)')),
                ('applies_to_plaque', models.BooleanField(default=False, help_text='Si applica alla singola placca (es. magnete)')),
                ('icon', models.CharField(default='Plus', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Add-on',
                'verbose_name_plural': 'Add-ons',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('discount_type', models.CharField(choices=[('copy_discount', 'Sconto copie (stessa placca)'), ('bundle_discount', 'Sconto bundle (multi-profilo)')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('min_items', models.PositiveIntegerField(default=1, help_text='Numero minimo di elementi per attivare lo sconto')),
                ('max_items', models.PositiveIntegerField(blank=True, help_text='Numero massimo di elementi (null = illimitato)', null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Percentuale di sconto (es. 30 per 30%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('priority', models.PositiveIntegerField(default=0, help_text='Priorità (sconti con priorità maggiore si applicano prima)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Discount Rule',
                'verbose_name_plural': 'Discount Rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_it', models.CharField(blank=True, max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('name_es', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('description_it', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_es', models.TextField(blank=True)),
                ('has_video', models.BooleanField(default=False)),
                ('icon', models.CharField(default='Cloud', max_length=50)),
                ('color_class', models.CharField(default='text-blue-500', max_length=100)),
                ('gradient_class', models.CharField(default='from-blue-500 to-indigo-600', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan Type',
                'verbose_name_plural': 'Plan Types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlaqueMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_it', models.CharField(blank=True, max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('name_es', models.CharField(blank=True, max_length=100)),
                ('upgrade_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo upgrade dalla placca legno inclusa', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('additional_price', models.DecimalField(decimal_places=2, help_text='Prezzo per placche aggiuntive (prima degli sconti)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('icon', models.CharField(default='Square', max_length=50)),
                ('color_class', models.CharField(default='text-gray-500', max_length=100)),
                ('bg_color_class', models.CharField(default='bg-gray-50', max_length=100)),
                ('is_included', models.BooleanField(default=False, help_text='Materiale incluso nel piano base')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plaque Material',
                'verbose_name_plural': 'Plaque Materials',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('currency_symbol', models.CharField(default='€', max_length=5)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Importo minimo ordine', max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Soglia per spedizione gratuita', max_digits=10, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo spedizione standard', max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('22.00'), help_text='IVA in percentuale', max_digits=5)),
                ('prices_include_tax', models.BooleanField(default=True, help_text='I prezzi già includono IVA')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configuration',
            },
        ),
        migrations.CreateModel(
            name='StorageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_gb', models.DecimalField(decimal_places=2, help_text='Storage in GB (es. 0.25 per 250MB, 1 per 1GB)', max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, help_text='Prezzo in EUR (include 1 placca legno)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estimated_photos', models.PositiveIntegerField(default=0)),
                ('estimated_video_minutes', models.PositiveIntegerField(default=0)),
                ('estimated_audio_hours', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('plan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_options', to='pricing.plantype')),
            ],
            options={
                'verbose_name': 'Storage Option',
                'verbose_name_plural': 'Storage Options',
                'ordering': ['plan_type', 'sort_order', 'storage_gb'],
                'unique_together': {('plan_type', 'storage_gb')},
            },
        ),
    ]
