# Generated by Django 5.2.10 on 2026-01-17 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apichallengetoken',
            new_name='security_ap_token_6709a6_idx',
            old_name='security_ap_token_e8a123_idx',
        ),
        migrations.RenameIndex(
            model_name='apinonce',
            new_name='security_ap_nonce_664f2b_idx',
            old_name='security_ap_nonce_e8a123_idx',
        ),
        migrations.RenameIndex(
            model_name='apinonce',
            new_name='security_ap_token_i_f34678_idx',
            old_name='security_ap_token_e8a456_idx',
        ),
    ]
