# Generated by Django 6.0.1 on 2026-01-07 21:54

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('shipping_address_line1', models.CharField(max_length=255)),
                ('shipping_address_line2', models.CharField(blank=True, max_length=255)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_state', models.CharField(blank=True, max_length=100)),
                ('shipping_postal_code', models.CharField(max_length=20)),
                ('shipping_country', models.CharField(default='IT', max_length=2)),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('payment_pending', 'Pagamento in corso'), ('paid', 'Pagato'), ('processing', 'In lavorazione'), ('shipped', 'Spedito'), ('delivered', 'Consegnato'), ('cancelled', 'Annullato'), ('refunded', 'Rimborsato')], default='pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('plans_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('plaques_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('addons_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('copy_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('bundle_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('bundle_discount_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('language', models.CharField(default='it', max_length=5)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome della persona commemorata', max_length=200)),
                ('plan_type_slug', models.CharField(max_length=50)),
                ('storage_gb', models.DecimalField(decimal_places=2, max_digits=6)),
                ('plan_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extension_years', models.PositiveIntegerField(default=0)),
                ('extension_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('profile_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='orders.order')),
                ('plan_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_profiles', to='pricing.plantype')),
                ('storage_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_profiles', to='pricing.storageoption')),
            ],
            options={
                'verbose_name': 'Order Profile',
                'verbose_name_plural': 'Order Profiles',
                'ordering': ['order', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OrderPlaque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_slug', models.CharField(max_length=50)),
                ('is_included', models.BooleanField(default=False, help_text='Prima placca inclusa nel piano')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prezzo base (0 se inclusa)', max_digits=10)),
                ('upgrade_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo upgrade materiale', max_digits=10)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sconto copia (0.30 = 30%)', max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('has_magnet', models.BooleanField(default=False)),
                ('magnet_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('has_engraving', models.BooleanField(default=False)),
                ('engraving_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_plaques', to='pricing.plaquematerial')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaques', to='orders.orderprofile')),
            ],
            options={
                'verbose_name': 'Order Plaque',
                'verbose_name_plural': 'Order Plaques',
                'ordering': ['profile', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Status History',
                'verbose_name_plural': 'Order Status History',
                'ordering': ['-created_at'],
            },
        ),
    ]
